services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_notes
    ports:
      - "6543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ainotes-net

  backend:
    build:
      context: .
    restart: always
    depends_on:
      - db
    expose:
      - "3001"
    env_file:
      - /opt/ai-notes/backend/.env
    command: ["node", "dist/main"]
    networks:
      - ainotes-net

  frontend:
    build:
      context: ../frontend
    restart: always
    depends_on:
      - backend
    expose:
      - "3000"
    networks:
      - ainotes-net

  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ainotes-net
    restart: unless-stopped

volumes:
  db_data:
  traefik_letsencrypt:   

networks:
  ainotes-net:
